/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/wrangler.jsonc --include-runtime=false cloudflare/worker-configuration.d.ts` (hash: 90b3ff6ef0f784a124b7f9e16b57f7d5)
interface __BaseEnv_Env {
	FETCH_IP_LIMITER: RateLimit;
	VERCEL_ORIGIN: "https://ultimate-html-penpot-ext.vercel.app";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./front-proxy");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VERCEL_ORIGIN">> {}
}
